template: external-bridged-provider
provider: scaleway
organization: pulumiverse
major-version: 1
providerDefaultBranch: main
upstreamProviderOrg: scaleway
publishRegistry: false
enableAutoRelease: false
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
#license:
#  ignore:
    # Package is licensed under Apache 2.0 but license is not picked up correctly by the license detector
#    - github.com/OpenDNS/vegadns2client
pr-assign: ringods
