template: external-bridged-provider
provider: scaleway
organization: pulumiverse
major-version: 1
providerDefaultBranch: main
upstreamProviderOrg: scaleway
publishRegistry: false
plugins:
    - name: terraform
      version: "1.0.19"
      kind: converter
    - name: random
      version: "4.16.7"
    - name: aws
      version: "6.56.1"
    - name: gitlab
      version: "8.5.0"
    - name: local
      version: "0.1.5"
    - name: "null"
      version: "0.0.8"
languages:
    - dotnet
    - go
    - nodejs
    - python
publish:
    sdk: "all,!java"
    cdn: false
license:
    ignore:
        # Don't check for the license of the local shim package
        - github.com/scaleway/terraform-provider-scaleway/v2/shim
pulumiConvert: 1
