template: external-bridged-provider
provider: scaleway
organization: pulumiverse
major-version: 1
providerDefaultBranch: main
upstreamProviderOrg: scaleway
publishRegistry: false
languages:
    - dotnet
    - go
    - nodejs
    - python
publish:
    sdk: "all,!java"
    cdn: false
license:
    ignore:
        # Don't check for the license of the local shim package
        - github.com/scaleway/terraform-provider-scaleway/v2/shim
pulumiConvert: 1
