# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
  dir: provider
  main: ./cmd/pulumi-resource-scaleway/
  ldflags: -X github.com/jaxxstorm/pulumi-scaleway/provider/pkg/version.Version={{.Version}}
  binary: pulumi-resource-scaleway
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    files: [] # Empty
changelog:
  # set it to true if you wish to skip the changelog generation
  skip: true
