archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-scaleway
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/jaxxstorm/pulumi-scaleway/provider/v2/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-scaleway/
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
