// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Gets information about an Edge Services WAF (Web Application Firewall) stage.
 *
 * A WAF stage provides web application firewall protection for an Edge Services pipeline, inspecting HTTP requests and blocking malicious traffic based on a configurable paranoia level.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * // Retrieve an Edge Services WAF stage by its ID
 * const byId = scaleway.edgeservices.getWafStage({
 *     wafStageId: "11111111-1111-1111-1111-111111111111",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * // Retrieve an Edge Services WAF stage by pipeline ID
 * const byPipeline = scaleway.edgeservices.getWafStage({
 *     pipelineId: main.id,
 * });
 * ```
 */
export function getWafStage(args?: GetWafStageArgs, opts?: pulumi.InvokeOptions): Promise<GetWafStageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scaleway:edgeservices/getWafStage:getWafStage", {
        "pipelineId": args.pipelineId,
        "wafStageId": args.wafStageId,
    }, opts);
}

/**
 * A collection of arguments for invoking getWafStage.
 */
export interface GetWafStageArgs {
    /**
     * The ID of the pipeline.
     */
    pipelineId?: string;
    /**
     * The ID of the WAF stage. Conflicts with all filter arguments below.
     *
     * The following filter arguments are supported (cannot be used with `wafStageId`):
     */
    wafStageId?: string;
}

/**
 * A collection of values returned by getWafStage.
 */
export interface GetWafStageResult {
    readonly backendStageId: string;
    readonly createdAt: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly mode: string;
    readonly paranoiaLevel: number;
    readonly pipelineId?: string;
    readonly projectId: string;
    readonly updatedAt: string;
    readonly wafStageId?: string;
}
/**
 * Gets information about an Edge Services WAF (Web Application Firewall) stage.
 *
 * A WAF stage provides web application firewall protection for an Edge Services pipeline, inspecting HTTP requests and blocking malicious traffic based on a configurable paranoia level.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * // Retrieve an Edge Services WAF stage by its ID
 * const byId = scaleway.edgeservices.getWafStage({
 *     wafStageId: "11111111-1111-1111-1111-111111111111",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * // Retrieve an Edge Services WAF stage by pipeline ID
 * const byPipeline = scaleway.edgeservices.getWafStage({
 *     pipelineId: main.id,
 * });
 * ```
 */
export function getWafStageOutput(args?: GetWafStageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWafStageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("scaleway:edgeservices/getWafStage:getWafStage", {
        "pipelineId": args.pipelineId,
        "wafStageId": args.wafStageId,
    }, opts);
}

/**
 * A collection of arguments for invoking getWafStage.
 */
export interface GetWafStageOutputArgs {
    /**
     * The ID of the pipeline.
     */
    pipelineId?: pulumi.Input<string>;
    /**
     * The ID of the WAF stage. Conflicts with all filter arguments below.
     *
     * The following filter arguments are supported (cannot be used with `wafStageId`):
     */
    wafStageId?: pulumi.Input<string>;
}
