// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Scaleway.Outputs
{

    [OutputType]
    public sealed class DatabaseInstancePrivateNetwork
    {
        /// <summary>
        /// Whether or not the private network endpoint should be configured with IPAM
        /// </summary>
        public readonly bool? EnableIpam;
        /// <summary>
        /// The ID of the endpoint.
        /// </summary>
        public readonly string? EndpointId;
        /// <summary>
        /// Hostname of the endpoint.
        /// </summary>
        public readonly string? Hostname;
        /// <summary>
        /// IPv4 address on the network.
        /// </summary>
        public readonly string? Ip;
        /// <summary>
        /// The IP with the given mask within the private subnet
        /// </summary>
        public readonly string? IpNet;
        /// <summary>
        /// The name of the Database Instance.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The private network ID
        /// </summary>
        public readonly string PnId;
        /// <summary>
        /// Port in the Private Network.
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// The zone you want to attach the resource to
        /// </summary>
        public readonly string? Zone;

        [OutputConstructor]
        private DatabaseInstancePrivateNetwork(
            bool? enableIpam,

            string? endpointId,

            string? hostname,

            string? ip,

            string? ipNet,

            string? name,

            string pnId,

            int? port,

            string? zone)
        {
            EnableIpam = enableIpam;
            EndpointId = endpointId;
            Hostname = hostname;
            Ip = ip;
            IpNet = ipNet;
            Name = name;
            PnId = pnId;
            Port = port;
            Zone = zone;
        }
    }
}
