// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/internal"
)

// Gets information about a Public Gateway PAT rule. For further information, please see the
// [API documentation](https://www.scaleway.com/en/developers/api/public-gateway/#path-pat-rules-list-pat-rules).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/instance"
//	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/network"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			sg01, err := instance.NewSecurityGroup(ctx, "sg01", &instance.SecurityGroupArgs{
//				InboundDefaultPolicy:  pulumi.String("drop"),
//				OutboundDefaultPolicy: pulumi.String("accept"),
//				InboundRules: instance.SecurityGroupInboundRuleArray{
//					&instance.SecurityGroupInboundRuleArgs{
//						Action:   pulumi.String("accept"),
//						Port:     pulumi.Int(22),
//						Protocol: pulumi.String("TCP"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			srv01, err := instance.NewServer(ctx, "srv01", &instance.ServerArgs{
//				Name:            pulumi.String("my-server"),
//				Type:            pulumi.String("PLAY2-NANO"),
//				Image:           pulumi.String("ubuntu_jammy"),
//				SecurityGroupId: sg01.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			pn01, err := network.NewPrivateNetwork(ctx, "pn01", &network.PrivateNetworkArgs{
//				Name: pulumi.String("my-pn"),
//			})
//			if err != nil {
//				return err
//			}
//			pnic01, err := instance.NewPrivateNic(ctx, "pnic01", &instance.PrivateNicArgs{
//				ServerId:         srv01.ID(),
//				PrivateNetworkId: pn01.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			dhcp01, err := network.NewPublicGatewayDhcp(ctx, "dhcp01", &network.PublicGatewayDhcpArgs{
//				Subnet: pulumi.String("192.168.0.0/24"),
//			})
//			if err != nil {
//				return err
//			}
//			ip01, err := network.NewPublicGatewayIp(ctx, "ip01", nil)
//			if err != nil {
//				return err
//			}
//			pg01, err := network.NewPublicGateway(ctx, "pg01", &network.PublicGatewayArgs{
//				Name: pulumi.String("my-pg"),
//				Type: pulumi.String("VPC-GW-S"),
//				IpId: ip01.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			gn01, err := network.NewGatewayNetwork(ctx, "gn01", &network.GatewayNetworkArgs{
//				GatewayId:        pg01.ID(),
//				PrivateNetworkId: pn01.ID(),
//				DhcpId:           dhcp01.ID(),
//				CleanupDhcp:      pulumi.Bool(true),
//				EnableMasquerade: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			rsv01, err := network.NewPublicGatewayDhcpReservation(ctx, "rsv01", &network.PublicGatewayDhcpReservationArgs{
//				GatewayNetworkId: gn01.ID(),
//				MacAddress:       pnic01.MacAddress,
//				IpAddress:        pulumi.String("192.168.0.7"),
//			})
//			if err != nil {
//				return err
//			}
//			pat01, err := network.NewPublicGatewayPatRule(ctx, "pat01", &network.PublicGatewayPatRuleArgs{
//				GatewayId:   pg01.ID(),
//				PrivateIp:   rsv01.IpAddress,
//				PrivatePort: pulumi.Int(22),
//				PublicPort:  pulumi.Int(2202),
//				Protocol:    pulumi.String("tcp"),
//			})
//			if err != nil {
//				return err
//			}
//			_ = network.LookupPublicGatewayPatRuleOutput(ctx, network.GetPublicGatewayPatRuleOutputArgs{
//				PatRuleId: pat01.ID(),
//			}, nil)
//			return nil
//		})
//	}
//
// ```
//
// Deprecated: scaleway.index/getvpcpublicpatrule.getVpcPublicPatRule has been deprecated in favor of scaleway.network/getpublicgatewaypatrule.getPublicGatewayPatRule
func GetVpcPublicPatRule(ctx *pulumi.Context, args *GetVpcPublicPatRuleArgs, opts ...pulumi.InvokeOption) (*GetVpcPublicPatRuleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVpcPublicPatRuleResult
	err := ctx.Invoke("scaleway:index/getVpcPublicPatRule:getVpcPublicPatRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcPublicPatRule.
type GetVpcPublicPatRuleArgs struct {
	// The ID of the PAT rule to retrieve
	PatRuleId string `pulumi:"patRuleId"`
	// `zone`) The zone in which
	// the rule exists.
	Zone *string `pulumi:"zone"`
}

// A collection of values returned by getVpcPublicPatRule.
type GetVpcPublicPatRuleResult struct {
	CreatedAt string `pulumi:"createdAt"`
	// The ID of the Public Gateway.
	GatewayId string `pulumi:"gatewayId"`
	// The provider-assigned unique ID for this managed resource.
	Id             string `pulumi:"id"`
	OrganizationId string `pulumi:"organizationId"`
	PatRuleId      string `pulumi:"patRuleId"`
	// The private IP address to forward data to.
	PrivateIp string `pulumi:"privateIp"`
	// The private port to translate to.
	PrivatePort int `pulumi:"privatePort"`
	// The protocol the rule should apply to. Possible values are `both`, `tcp` and `udp`.
	Protocol string `pulumi:"protocol"`
	// The public port to listen on.
	PublicPort int     `pulumi:"publicPort"`
	UpdatedAt  string  `pulumi:"updatedAt"`
	Zone       *string `pulumi:"zone"`
}

func GetVpcPublicPatRuleOutput(ctx *pulumi.Context, args GetVpcPublicPatRuleOutputArgs, opts ...pulumi.InvokeOption) GetVpcPublicPatRuleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVpcPublicPatRuleResultOutput, error) {
			args := v.(GetVpcPublicPatRuleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scaleway:index/getVpcPublicPatRule:getVpcPublicPatRule", args, GetVpcPublicPatRuleResultOutput{}, options).(GetVpcPublicPatRuleResultOutput), nil
		}).(GetVpcPublicPatRuleResultOutput)
}

// A collection of arguments for invoking getVpcPublicPatRule.
type GetVpcPublicPatRuleOutputArgs struct {
	// The ID of the PAT rule to retrieve
	PatRuleId pulumi.StringInput `pulumi:"patRuleId"`
	// `zone`) The zone in which
	// the rule exists.
	Zone pulumi.StringPtrInput `pulumi:"zone"`
}

func (GetVpcPublicPatRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcPublicPatRuleArgs)(nil)).Elem()
}

// A collection of values returned by getVpcPublicPatRule.
type GetVpcPublicPatRuleResultOutput struct{ *pulumi.OutputState }

func (GetVpcPublicPatRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcPublicPatRuleResult)(nil)).Elem()
}

func (o GetVpcPublicPatRuleResultOutput) ToGetVpcPublicPatRuleResultOutput() GetVpcPublicPatRuleResultOutput {
	return o
}

func (o GetVpcPublicPatRuleResultOutput) ToGetVpcPublicPatRuleResultOutputWithContext(ctx context.Context) GetVpcPublicPatRuleResultOutput {
	return o
}

func (o GetVpcPublicPatRuleResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The ID of the Public Gateway.
func (o GetVpcPublicPatRuleResultOutput) GatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.GatewayId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVpcPublicPatRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVpcPublicPatRuleResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetVpcPublicPatRuleResultOutput) PatRuleId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.PatRuleId }).(pulumi.StringOutput)
}

// The private IP address to forward data to.
func (o GetVpcPublicPatRuleResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

// The private port to translate to.
func (o GetVpcPublicPatRuleResultOutput) PrivatePort() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) int { return v.PrivatePort }).(pulumi.IntOutput)
}

// The protocol the rule should apply to. Possible values are `both`, `tcp` and `udp`.
func (o GetVpcPublicPatRuleResultOutput) Protocol() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.Protocol }).(pulumi.StringOutput)
}

// The public port to listen on.
func (o GetVpcPublicPatRuleResultOutput) PublicPort() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) int { return v.PublicPort }).(pulumi.IntOutput)
}

func (o GetVpcPublicPatRuleResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o GetVpcPublicPatRuleResultOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVpcPublicPatRuleResult) *string { return v.Zone }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVpcPublicPatRuleResultOutput{})
}
