// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/internal"
)

// Creates and manages users on a Scaleway MessageQ deployment.
// For more information refer to the [API documentation](https://www.scaleway.com/en/developers/api/messageq).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			main, err := scaleway.NewMessageqDeployment(ctx, "main", &scaleway.MessageqDeploymentArgs{
//				Name:      pulumi.String("my-messageq"),
//				Version:   pulumi.String("4.0"),
//				NodeCount: pulumi.Int(1),
//				NodeType:  pulumi.String("MESSAGEQ-SHARED-2C-8G"),
//				UserName:  pulumi.String("admin"),
//				Password:  pulumi.String("ThisIsASecurePassword123!"),
//				Volume: &scaleway.MessageqDeploymentVolumeArgs{
//					Type:     pulumi.String("sbs_5k"),
//					SizeInGb: pulumi.Int(5),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = scaleway.NewMessageqUser(ctx, "app", &scaleway.MessageqUserArgs{
//				DeploymentId: main.ID().ToIDOutput().ToStringOutput(),
//				Name:         pulumi.String("orders-app"),
//				Password:     pulumi.Any(appPassword),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// MessageQ users can be imported using `{region}/{deployment_id}/{name}`, e.g.
//
// ```sh
// $ pulumi import scaleway:index/messageqUser:MessageqUser app fr-par/11111111-1111-1111-1111-111111111111/orders-app
// ```
type MessageqUser struct {
	pulumi.CustomResourceState

	// The ID of the MessageQ deployment.
	DeploymentId pulumi.StringOutput `pulumi:"deploymentId"`
	// The username.
	Name pulumi.StringOutput `pulumi:"name"`
	// The user password. Only one of `password` or `passwordWo` should be specified.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
	PasswordWo pulumi.StringPtrOutput `pulumi:"passwordWo"`
	// Version of the write-only password. Required with `passwordWo`.
	PasswordWoVersion pulumi.IntPtrOutput `pulumi:"passwordWoVersion"`
	// `region`) The region in which the user should be created.
	Region pulumi.StringOutput `pulumi:"region"`
}

// NewMessageqUser registers a new resource with the given unique name, arguments, and options.
func NewMessageqUser(ctx *pulumi.Context,
	name string, args *MessageqUserArgs, opts ...pulumi.ResourceOption) (*MessageqUser, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DeploymentId == nil {
		return nil, errors.New("invalid value for required argument 'DeploymentId'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	if args.PasswordWo != nil {
		args.PasswordWo = pulumi.ToSecret(args.PasswordWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
		"passwordWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MessageqUser
	err := ctx.RegisterResource("scaleway:index/messageqUser:MessageqUser", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMessageqUser gets an existing MessageqUser resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMessageqUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MessageqUserState, opts ...pulumi.ResourceOption) (*MessageqUser, error) {
	var resource MessageqUser
	err := ctx.ReadResource("scaleway:index/messageqUser:MessageqUser", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MessageqUser resources.
type messageqUserState struct {
	// The ID of the MessageQ deployment.
	DeploymentId *string `pulumi:"deploymentId"`
	// The username.
	Name *string `pulumi:"name"`
	// The user password. Only one of `password` or `passwordWo` should be specified.
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version of the write-only password. Required with `passwordWo`.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// `region`) The region in which the user should be created.
	Region *string `pulumi:"region"`
}

type MessageqUserState struct {
	// The ID of the MessageQ deployment.
	DeploymentId pulumi.StringPtrInput
	// The username.
	Name pulumi.StringPtrInput
	// The user password. Only one of `password` or `passwordWo` should be specified.
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
	PasswordWo pulumi.StringPtrInput
	// Version of the write-only password. Required with `passwordWo`.
	PasswordWoVersion pulumi.IntPtrInput
	// `region`) The region in which the user should be created.
	Region pulumi.StringPtrInput
}

func (MessageqUserState) ElementType() reflect.Type {
	return reflect.TypeOf((*messageqUserState)(nil)).Elem()
}

type messageqUserArgs struct {
	// The ID of the MessageQ deployment.
	DeploymentId string `pulumi:"deploymentId"`
	// The username.
	Name *string `pulumi:"name"`
	// The user password. Only one of `password` or `passwordWo` should be specified.
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version of the write-only password. Required with `passwordWo`.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// `region`) The region in which the user should be created.
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a MessageqUser resource.
type MessageqUserArgs struct {
	// The ID of the MessageQ deployment.
	DeploymentId pulumi.StringInput
	// The username.
	Name pulumi.StringPtrInput
	// The user password. Only one of `password` or `passwordWo` should be specified.
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
	PasswordWo pulumi.StringPtrInput
	// Version of the write-only password. Required with `passwordWo`.
	PasswordWoVersion pulumi.IntPtrInput
	// `region`) The region in which the user should be created.
	Region pulumi.StringPtrInput
}

func (MessageqUserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*messageqUserArgs)(nil)).Elem()
}

type MessageqUserInput interface {
	pulumi.Input

	ToMessageqUserOutput() MessageqUserOutput
	ToMessageqUserOutputWithContext(ctx context.Context) MessageqUserOutput
}

func (*MessageqUser) ElementType() reflect.Type {
	return reflect.TypeOf((**MessageqUser)(nil)).Elem()
}

func (i *MessageqUser) ToMessageqUserOutput() MessageqUserOutput {
	return i.ToMessageqUserOutputWithContext(context.Background())
}

func (i *MessageqUser) ToMessageqUserOutputWithContext(ctx context.Context) MessageqUserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MessageqUserOutput)
}

// MessageqUserArrayInput is an input type that accepts MessageqUserArray and MessageqUserArrayOutput values.
// You can construct a concrete instance of `MessageqUserArrayInput` via:
//
//	MessageqUserArray{ MessageqUserArgs{...} }
type MessageqUserArrayInput interface {
	pulumi.Input

	ToMessageqUserArrayOutput() MessageqUserArrayOutput
	ToMessageqUserArrayOutputWithContext(context.Context) MessageqUserArrayOutput
}

type MessageqUserArray []MessageqUserInput

func (MessageqUserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MessageqUser)(nil)).Elem()
}

func (i MessageqUserArray) ToMessageqUserArrayOutput() MessageqUserArrayOutput {
	return i.ToMessageqUserArrayOutputWithContext(context.Background())
}

func (i MessageqUserArray) ToMessageqUserArrayOutputWithContext(ctx context.Context) MessageqUserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MessageqUserArrayOutput)
}

// MessageqUserMapInput is an input type that accepts MessageqUserMap and MessageqUserMapOutput values.
// You can construct a concrete instance of `MessageqUserMapInput` via:
//
//	MessageqUserMap{ "key": MessageqUserArgs{...} }
type MessageqUserMapInput interface {
	pulumi.Input

	ToMessageqUserMapOutput() MessageqUserMapOutput
	ToMessageqUserMapOutputWithContext(context.Context) MessageqUserMapOutput
}

type MessageqUserMap map[string]MessageqUserInput

func (MessageqUserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MessageqUser)(nil)).Elem()
}

func (i MessageqUserMap) ToMessageqUserMapOutput() MessageqUserMapOutput {
	return i.ToMessageqUserMapOutputWithContext(context.Background())
}

func (i MessageqUserMap) ToMessageqUserMapOutputWithContext(ctx context.Context) MessageqUserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MessageqUserMapOutput)
}

type MessageqUserOutput struct{ *pulumi.OutputState }

func (MessageqUserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MessageqUser)(nil)).Elem()
}

func (o MessageqUserOutput) ToMessageqUserOutput() MessageqUserOutput {
	return o
}

func (o MessageqUserOutput) ToMessageqUserOutputWithContext(ctx context.Context) MessageqUserOutput {
	return o
}

// The ID of the MessageQ deployment.
func (o MessageqUserOutput) DeploymentId() pulumi.StringOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.StringOutput { return v.DeploymentId }).(pulumi.StringOutput)
}

// The username.
func (o MessageqUserOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The user password. Only one of `password` or `passwordWo` should be specified.
func (o MessageqUserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// The user password in write-only mode. Only one of `password` or `passwordWo` should be specified. To rotate the password, update both `passwordWo` and `passwordWoVersion`.
func (o MessageqUserOutput) PasswordWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.StringPtrOutput { return v.PasswordWo }).(pulumi.StringPtrOutput)
}

// Version of the write-only password. Required with `passwordWo`.
func (o MessageqUserOutput) PasswordWoVersion() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.IntPtrOutput { return v.PasswordWoVersion }).(pulumi.IntPtrOutput)
}

// `region`) The region in which the user should be created.
func (o MessageqUserOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *MessageqUser) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

type MessageqUserArrayOutput struct{ *pulumi.OutputState }

func (MessageqUserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MessageqUser)(nil)).Elem()
}

func (o MessageqUserArrayOutput) ToMessageqUserArrayOutput() MessageqUserArrayOutput {
	return o
}

func (o MessageqUserArrayOutput) ToMessageqUserArrayOutputWithContext(ctx context.Context) MessageqUserArrayOutput {
	return o
}

func (o MessageqUserArrayOutput) Index(i pulumi.IntInput) MessageqUserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MessageqUser {
		return vs[0].([]*MessageqUser)[vs[1].(int)]
	}).(MessageqUserOutput)
}

type MessageqUserMapOutput struct{ *pulumi.OutputState }

func (MessageqUserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MessageqUser)(nil)).Elem()
}

func (o MessageqUserMapOutput) ToMessageqUserMapOutput() MessageqUserMapOutput {
	return o
}

func (o MessageqUserMapOutput) ToMessageqUserMapOutputWithContext(ctx context.Context) MessageqUserMapOutput {
	return o
}

func (o MessageqUserMapOutput) MapIndex(k pulumi.StringInput) MessageqUserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MessageqUser {
		return vs[0].(map[string]*MessageqUser)[vs[1].(string)]
	}).(MessageqUserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MessageqUserInput)(nil)).Elem(), &MessageqUser{})
	pulumi.RegisterInputType(reflect.TypeOf((*MessageqUserArrayInput)(nil)).Elem(), MessageqUserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MessageqUserMapInput)(nil)).Elem(), MessageqUserMap{})
	pulumi.RegisterOutputType(MessageqUserOutput{})
	pulumi.RegisterOutputType(MessageqUserArrayOutput{})
	pulumi.RegisterOutputType(MessageqUserMapOutput{})
}
