// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Scaleway.Domain.Inputs
{

    public sealed class RegistrationTechnicalContactExtensionFrAssociationInfoGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Publication date in the Official Journal (RFC3339 format) for association information.
        /// </summary>
        [Input("publicationJo")]
        public Input<string>? PublicationJo { get; set; }

        /// <summary>
        /// Page number of the publication in the Official Journal for association information.
        /// </summary>
        [Input("publicationJoPage")]
        public Input<int>? PublicationJoPage { get; set; }

        public RegistrationTechnicalContactExtensionFrAssociationInfoGetArgs()
        {
        }
        public static new RegistrationTechnicalContactExtensionFrAssociationInfoGetArgs Empty => new RegistrationTechnicalContactExtensionFrAssociationInfoGetArgs();
    }
}
