// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodb

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/internal"
)

// Creates and manages Scaleway MongoDB® users.
// For more information refer to the [product documentation](https://www.scaleway.com/en/docs/managed-mongodb-databases/).
//
// ## Example Usage
//
// ### Basic
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/mongodb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			main, err := mongodb.NewInstance(ctx, "main", &mongodb.InstanceArgs{
//				Name:           pulumi.String("test-mongodb-user"),
//				Version:        pulumi.String("7.0.12"),
//				NodeType:       pulumi.String("MGDB-PLAY2-NANO"),
//				NodeNumber:     pulumi.Int(1),
//				UserName:       pulumi.String("initial_user"),
//				Password:       pulumi.String("initial_password123"),
//				VolumeSizeInGb: pulumi.Int(5),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = mongodb.NewUser(ctx, "main", &mongodb.UserArgs{
//				InstanceId: main.ID(),
//				Name:       pulumi.String("my_user"),
//				Password:   pulumi.String("my_password123"),
//				Roles: mongodb.UserRoleArray{
//					&mongodb.UserRoleArgs{
//						Role:         pulumi.String("read_write"),
//						DatabaseName: pulumi.String("my_database"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### With Multiple Users
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-scaleway/sdk/go/scaleway/mongodb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			main, err := mongodb.NewInstance(ctx, "main", &mongodb.InstanceArgs{
//				Name:           pulumi.String("test-mongodb-multi-user"),
//				Version:        pulumi.String("7.0.12"),
//				NodeType:       pulumi.String("MGDB-PLAY2-NANO"),
//				NodeNumber:     pulumi.Int(1),
//				UserName:       pulumi.String("admin_user"),
//				Password:       pulumi.String("admin_password123"),
//				VolumeSizeInGb: pulumi.Int(5),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = mongodb.NewUser(ctx, "app_user", &mongodb.UserArgs{
//				InstanceId: main.ID(),
//				Name:       pulumi.String("app_user"),
//				Password:   pulumi.String("app_password123"),
//				Roles: mongodb.UserRoleArray{
//					&mongodb.UserRoleArgs{
//						Role:         pulumi.String("read_write"),
//						DatabaseName: pulumi.String("app_database"),
//					},
//					&mongodb.UserRoleArgs{
//						Role:         pulumi.String("read"),
//						DatabaseName: pulumi.String("logs_database"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = mongodb.NewUser(ctx, "admin_user", &mongodb.UserArgs{
//				InstanceId: main.ID(),
//				Name:       pulumi.String("admin_user"),
//				Password:   pulumi.String("admin_password123"),
//				Roles: mongodb.UserRoleArray{
//					&mongodb.UserRoleArgs{
//						Role:         pulumi.String("db_admin"),
//						DatabaseName: pulumi.String("admin"),
//					},
//					&mongodb.UserRoleArgs{
//						Role:        pulumi.String("read"),
//						AnyDatabase: pulumi.Bool(true),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// MongoDB® users can be imported using the `{region}/{instance_id}/{name}`, e.g.
//
// bash
//
// ```sh
// $ pulumi import scaleway:mongodb/user:User main fr-par/11111111-1111-1111-1111-111111111111/my_user
// ```
type User struct {
	pulumi.CustomResourceState

	// The ID of the MongoDB® instance.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// The name of the MongoDB® user.
	Name pulumi.StringOutput `pulumi:"name"`
	// The password of the MongoDB® user.
	Password pulumi.StringOutput `pulumi:"password"`
	// `region`) The region in which the MongoDB® user should be created.
	Region pulumi.StringPtrOutput `pulumi:"region"`
	// List of roles assigned to the user. Each role block supports:
	Roles UserRoleArrayOutput `pulumi:"roles"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("scaleway:mongodb/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("scaleway:mongodb/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// The ID of the MongoDB® instance.
	InstanceId *string `pulumi:"instanceId"`
	// The name of the MongoDB® user.
	Name *string `pulumi:"name"`
	// The password of the MongoDB® user.
	Password *string `pulumi:"password"`
	// `region`) The region in which the MongoDB® user should be created.
	Region *string `pulumi:"region"`
	// List of roles assigned to the user. Each role block supports:
	Roles []UserRole `pulumi:"roles"`
}

type UserState struct {
	// The ID of the MongoDB® instance.
	InstanceId pulumi.StringPtrInput
	// The name of the MongoDB® user.
	Name pulumi.StringPtrInput
	// The password of the MongoDB® user.
	Password pulumi.StringPtrInput
	// `region`) The region in which the MongoDB® user should be created.
	Region pulumi.StringPtrInput
	// List of roles assigned to the user. Each role block supports:
	Roles UserRoleArrayInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// The ID of the MongoDB® instance.
	InstanceId string `pulumi:"instanceId"`
	// The name of the MongoDB® user.
	Name *string `pulumi:"name"`
	// The password of the MongoDB® user.
	Password string `pulumi:"password"`
	// `region`) The region in which the MongoDB® user should be created.
	Region *string `pulumi:"region"`
	// List of roles assigned to the user. Each role block supports:
	Roles []UserRole `pulumi:"roles"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// The ID of the MongoDB® instance.
	InstanceId pulumi.StringInput
	// The name of the MongoDB® user.
	Name pulumi.StringPtrInput
	// The password of the MongoDB® user.
	Password pulumi.StringInput
	// `region`) The region in which the MongoDB® user should be created.
	Region pulumi.StringPtrInput
	// List of roles assigned to the user. Each role block supports:
	Roles UserRoleArrayInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//	UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//	UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// The ID of the MongoDB® instance.
func (o UserOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// The name of the MongoDB® user.
func (o UserOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The password of the MongoDB® user.
func (o UserOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// `region`) The region in which the MongoDB® user should be created.
func (o UserOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

// List of roles assigned to the user. Each role block supports:
func (o UserOutput) Roles() UserRoleArrayOutput {
	return o.ApplyT(func(v *User) UserRoleArrayOutput { return v.Roles }).(UserRoleArrayOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
