// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates and manages Scaleway Database Private Network Endpoint.
 * For more information, see [the documentation](https://www.scaleway.com/en/developers/api/document_db/).
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Database Instance Endpoint can be imported using the `{region}/{endpoint_id}`, e.g.
 *
 * bash
 *
 * ```sh
 * $ pulumi import scaleway:index/documentdbPrivateNetworkEndpoint:DocumentdbPrivateNetworkEndpoint end fr-par/11111111-1111-1111-1111-111111111111
 * ```
 */
export class DocumentdbPrivateNetworkEndpoint extends pulumi.CustomResource {
    /**
     * Get an existing DocumentdbPrivateNetworkEndpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DocumentdbPrivateNetworkEndpointState, opts?: pulumi.CustomResourceOptions): DocumentdbPrivateNetworkEndpoint {
        return new DocumentdbPrivateNetworkEndpoint(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'scaleway:index/documentdbPrivateNetworkEndpoint:DocumentdbPrivateNetworkEndpoint';

    /**
     * Returns true if the given object is an instance of DocumentdbPrivateNetworkEndpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DocumentdbPrivateNetworkEndpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DocumentdbPrivateNetworkEndpoint.__pulumiType;
    }

    /**
     * Hostname of the endpoint.
     */
    public /*out*/ readonly hostname!: pulumi.Output<string>;
    /**
     * UUID of the documentdb instance.
     */
    public readonly instanceId!: pulumi.Output<string>;
    /**
     * IPv4 address on the network.
     */
    public /*out*/ readonly ip!: pulumi.Output<string>;
    /**
     * The IP network address within the private subnet. This must be an IPv4 address with a
     * CIDR notation. The IP network address within the private subnet is determined by the IP Address Management (IPAM)
     * service if not set.
     */
    public readonly ipNet!: pulumi.Output<string>;
    /**
     * Name of the endpoint.
     */
    public /*out*/ readonly name!: pulumi.Output<string>;
    /**
     * Port in the Private Network.
     */
    public readonly port!: pulumi.Output<number>;
    /**
     * The ID of the private network.
     */
    public readonly privateNetworkId!: pulumi.Output<string>;
    /**
     * The region you want to attach the resource to
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * The zone you want to attach the resource to
     */
    public readonly zone!: pulumi.Output<string>;

    /**
     * Create a DocumentdbPrivateNetworkEndpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DocumentdbPrivateNetworkEndpointArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DocumentdbPrivateNetworkEndpointArgs | DocumentdbPrivateNetworkEndpointState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DocumentdbPrivateNetworkEndpointState | undefined;
            resourceInputs["hostname"] = state ? state.hostname : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["ip"] = state ? state.ip : undefined;
            resourceInputs["ipNet"] = state ? state.ipNet : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["privateNetworkId"] = state ? state.privateNetworkId : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["zone"] = state ? state.zone : undefined;
        } else {
            const args = argsOrState as DocumentdbPrivateNetworkEndpointArgs | undefined;
            if ((!args || args.instanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            if ((!args || args.privateNetworkId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'privateNetworkId'");
            }
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["ipNet"] = args ? args.ipNet : undefined;
            resourceInputs["port"] = args ? args.port : undefined;
            resourceInputs["privateNetworkId"] = args ? args.privateNetworkId : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["zone"] = args ? args.zone : undefined;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DocumentdbPrivateNetworkEndpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DocumentdbPrivateNetworkEndpoint resources.
 */
export interface DocumentdbPrivateNetworkEndpointState {
    /**
     * Hostname of the endpoint.
     */
    hostname?: pulumi.Input<string>;
    /**
     * UUID of the documentdb instance.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * IPv4 address on the network.
     */
    ip?: pulumi.Input<string>;
    /**
     * The IP network address within the private subnet. This must be an IPv4 address with a
     * CIDR notation. The IP network address within the private subnet is determined by the IP Address Management (IPAM)
     * service if not set.
     */
    ipNet?: pulumi.Input<string>;
    /**
     * Name of the endpoint.
     */
    name?: pulumi.Input<string>;
    /**
     * Port in the Private Network.
     */
    port?: pulumi.Input<number>;
    /**
     * The ID of the private network.
     */
    privateNetworkId?: pulumi.Input<string>;
    /**
     * The region you want to attach the resource to
     */
    region?: pulumi.Input<string>;
    /**
     * The zone you want to attach the resource to
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DocumentdbPrivateNetworkEndpoint resource.
 */
export interface DocumentdbPrivateNetworkEndpointArgs {
    /**
     * UUID of the documentdb instance.
     */
    instanceId: pulumi.Input<string>;
    /**
     * The IP network address within the private subnet. This must be an IPv4 address with a
     * CIDR notation. The IP network address within the private subnet is determined by the IP Address Management (IPAM)
     * service if not set.
     */
    ipNet?: pulumi.Input<string>;
    /**
     * Port in the Private Network.
     */
    port?: pulumi.Input<number>;
    /**
     * The ID of the private network.
     */
    privateNetworkId: pulumi.Input<string>;
    /**
     * The region you want to attach the resource to
     */
    region?: pulumi.Input<string>;
    /**
     * The zone you want to attach the resource to
     */
    zone?: pulumi.Input<string>;
}
