// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about an annotation binding.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * const environment = new scaleway.AnnotationsKey("environment", {
 *     name: "environment",
 *     description: "Deployment environment (production, staging, development)",
 * });
 * const production = new scaleway.AnnotationsValue("production", {
 *     keyId: environment.id,
 *     name: "production",
 *     description: "Production environment",
 * });
 * const mainKey = new scaleway.keymanager.Key("main", {
 *     name: "example-key",
 *     region: "fr-par",
 *     usage: "symmetric_encryption",
 *     algorithm: "aes_256_gcm",
 *     description: "Example key for binding",
 *     unprotected: true,
 * });
 * const mainAnnotationsBinding = new scaleway.AnnotationsBinding("main", {
 *     srn: mainKey.srn,
 *     valueId: production.id,
 * });
 * const main = scaleway.getAnnotationsBindingOutput({
 *     bindingId: mainAnnotationsBinding.id,
 * });
 * ```
 */
export function getAnnotationsBinding(args: GetAnnotationsBindingArgs, opts?: pulumi.InvokeOptions): Promise<GetAnnotationsBindingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scaleway:index/getAnnotationsBinding:getAnnotationsBinding", {
        "bindingId": args.bindingId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAnnotationsBinding.
 */
export interface GetAnnotationsBindingArgs {
    /**
     * The ID of the annotation binding to retrieve.
     */
    bindingId: string;
}

/**
 * A collection of values returned by getAnnotationsBinding.
 */
export interface GetAnnotationsBindingResult {
    readonly bindingId: string;
    /**
     * The ID of the annotation binding
     */
    readonly id: string;
    /**
     * ID of the key associated to the binding
     */
    readonly keyId: string;
    /**
     * Scaleway Resource Number associated to the binding
     */
    readonly srn: string;
    /**
     * ID of the value associated to the binding
     */
    readonly valueId: string;
}
/**
 * Use this data source to retrieve information about an annotation binding.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumiverse/scaleway";
 *
 * const environment = new scaleway.AnnotationsKey("environment", {
 *     name: "environment",
 *     description: "Deployment environment (production, staging, development)",
 * });
 * const production = new scaleway.AnnotationsValue("production", {
 *     keyId: environment.id,
 *     name: "production",
 *     description: "Production environment",
 * });
 * const mainKey = new scaleway.keymanager.Key("main", {
 *     name: "example-key",
 *     region: "fr-par",
 *     usage: "symmetric_encryption",
 *     algorithm: "aes_256_gcm",
 *     description: "Example key for binding",
 *     unprotected: true,
 * });
 * const mainAnnotationsBinding = new scaleway.AnnotationsBinding("main", {
 *     srn: mainKey.srn,
 *     valueId: production.id,
 * });
 * const main = scaleway.getAnnotationsBindingOutput({
 *     bindingId: mainAnnotationsBinding.id,
 * });
 * ```
 */
export function getAnnotationsBindingOutput(args: GetAnnotationsBindingOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAnnotationsBindingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("scaleway:index/getAnnotationsBinding:getAnnotationsBinding", {
        "bindingId": args.bindingId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAnnotationsBinding.
 */
export interface GetAnnotationsBindingOutputArgs {
    /**
     * The ID of the annotation binding to retrieve.
     */
    bindingId: pulumi.Input<string>;
}
